### ISSUE TITLE
hi 这么棒，为什么不维护了呢？

### ISSUE THREAD

**Issue by wy19901227** [was0107/Layout#1]
你现在也是在用apple的autolayout了吗？在autolayout之前，由于项目需求 我就写过一个竖直排列的pannel，不需要知道y坐标，按顺序添加就会按顺序向下排列，当然，利用了kvo当你改变了某一个subview的frame，会重新排列，设置hidden会自动向上顶。
看了你的这个，就像css一样吧，好全面。
半年前，我一直使用antolayout，用的也不错了，也有一些开源的关于antolayout的类，当你需要隐藏一个view，不需要重新写约束，也挺方便，关键是在sb中用非常直观。
但是最近我又放弃了autolayout，原因就是apple最近的系统太烂了，各种卡顿，不流畅，必须自己优化，但是就不能使用autolayout了，所以我又重新用frame。然后看到你这个东西，觉得很棒，希望作者可以继续维护。

**Comment by was0107** [comment]
今天闲来无事，将之前的UML图放上了，且以FRAMEWORK的形式进行提供。
autolayout作为Apple推荐的做法，还是尽量使用；
